[package]
name = "euphoria"
version = "0.1.0"
edition = "2021"
author = "Ivan Chien <qyc027@gmail.com>"

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
glob = "0.3.1"
uuid = { version = "1.3.1", features = ["v4", "serde"] }
